analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_double_quotes: true