name: "Build Flatpaks"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  build-flatpak:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lix GHA Installer Action
        uses: samueldr/lix-gha-installer-action@v2026-02-22
        with:
          extra_nix_config: experimental-features = nix-command flakes flake-self-attrs

      - name: Build app
        run: nix build .#flatpak

      - name: Upload installer artifact
        uses: actions/upload-artifact@v6
        with:
          name: flatpak-${{ matrix.arch }}
          path: result/nexus.federated.Nexus.flatpak