name: "Build MacOS App"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Lix GHA Installer Action
        uses: samueldr/lix-gha-installer-action@v2026-02-22
        with:
          extra_nix_config: experimental-features = nix-command flakes flake-self-attrs

      - name: Build app
        run: nix build .#default

      - name: Upload installer artifact
        uses: actions/upload-artifact@v6
        with:
          name: flatpak-${{ matrix.arch }}
          path: result/Nexus.app