name: "Build MacOS App"

on:
    push:
        branches: ["main"]
        tags: ["*"]
    workflow_dispatch:

jobs:
    build-app:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  submodules: recursive

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.44.4

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: gomuks/go.mod

            - name: Build app
              run: |
                  flutter pub get
                  dart scripts/generate.dart
                  flutter pub run build_runner build
                  flutter build macos --release

            - name: Upload installer artifact
              uses: actions/upload-artifact@v6
              with:
                  name: Nexus.App
                  path: build/macos/Build/Products/Release/Nexus.app

            - name: Create DMG
              uses: L-Super/create-dmg-actions@v1
              with:
                  dmg_name: nexus.dmg
                  src_dir: Nexus.app

            - name: Upload installer artifact
              uses: actions/upload-artifact@v6
              with:
                  name: ${{ steps.create-dmg.inputs.path }}
                  path: ${{ github.workspace }}/${{ steps.create-dmg.outputs.dmg_path }}
