name: "Build MacOS App"

on:
    push:
        branches: ["main"]
        tags: ["*"]
    workflow_dispatch:

jobs:
    build-app:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              with:
                  submodules: recursive

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.44.4

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: gomuks/go.mod

            - name: Build App
              run: |
                  flutter pub get
                  dart scripts/generate.dart
                  flutter pub run build_runner build
                  flutter build macos --release

            - name: Create DMG
              id: create-dmg
              uses: L-Super/create-dmg-actions@28511e988b13ca34096d439159a66d468b8e724f
              with:
                  dmg_name: nexus
                  src_dir: build/macos/Build/Products/Release/Nexus.app

            - name: Upload DMG
              uses: actions/upload-artifact@v6
              with:
                  name: nexus.dmg
                  path: ${{ steps.create-dmg.outputs.dmg_path }}
