name: "Build EXE"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up Go
        uses: actions/setup-go@v6

      - name: Run build_runner & build Windows EXE
        run: |
          dart scripts/generate.dart
          flutter pub run build_runner build
          flutter build windows --release

      - name: Upload exe zip
        uses: actions/upload-artifact@v6
        with:
          name: windows-portable
          path: build/windows/x64/runner/Release/

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Inno Setup installer
        run: iscc windows/installer.iss

      - name: Upload installer artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-installer
          path: windows/dist/Nexus-Setup.exe